// src/App.vue
<script setup lang="ts">
import ProductCard from './components/product-card.vue';



</script>

<template>
    <main class="container">
        <ProductCard />
    </main>

</template>

<style scoped>
.container {
    width: 100%;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
}
</style>

// src/App.svelte
<script lang="ts">
  import ProductCard from "./lib/product-card.svelte";
</script>

<main class="container">
  <ProductCard />
</main>

<style>
  .container {
    width: 100%;
    height: 100vh;
    overflow: hidden;
    display: flex;
    justify-content: center;
    align-items: center;
  }
</style>
